################################# Default configuration ###################
# provide your domain here
baseURL = "https://sysdp2021-t03cic.github.io/"
# theme
theme = "dot-hugo"
# site title
title = "システム創成2021 CIC担当チーム 引継ぎ資料"
# default language
defaultContentLanguage = 'jp'
# disable language
disableLanguages = []
# unsafe html
[markup.goldmark.renderer]
unsafe = true

publishDir = "docs"

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#1c7cc5"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
name = "Facebook"
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
name = "Twitter"
link = "#"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "#"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
name = "Linkedin"
link = "#"

################################ Japanese Language ######################
[Languages.jp]
languageName = "Jp"
languageCode = "ja-jp"
contentDir = "content/japanese"
weight = 1
copyright = "Copyright &copy; 2021 a Hugo theme by [Gethugothemes](https://gethugothemes.com/)"

# banner
[Languages.jp.params.banner]
title = "システム創成2021 CIC担当チーム\n引継ぎ資料"
subtitle = ""
bg_image = "images/banner.jpg"
placeholder = ""

# call to action
[Languages.jp.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
# call to action button
[Languages.jp.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################## japanese navigation #################
[[Languages.jp.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.jp.menu.main]]
name = "Faq"
url = "faq"
weight = 2

[[Languages.jp.menu.main]]
name = "contact"
url = "contact"
weight = 3

# Dropdown menu
[[Languages.jp.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.jp.menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation"
  weight = 1

  [[Languages.jp.menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing"
  weight = 2

  [[Languages.jp.menu.main]]
  parent = "docs"
  name = "Features"
  url = "features"
  weight = 3